services:
  aws-mcp:
    build:
      context: .
      target: prod
  aws-mcp-dev:
    build:
      context: .
      target: dev
    ports:
    - 6274:6274
    - 6277:6277
    tty: true
    volumes:
    #- ./lib:/app/lib
    - bun:/app/.bun
    - $HOME/.aws:/root/.aws

volumes:
  bun:
